const data = {
  products: [
    {
      _id: "1",
      name: "Name 1",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 50,
      brand: "Domace",
      rating: 4.5,
      numReviews: 10,
      description: "Height qualty product",
    },
    {
      _id: "2",
      name: "Name 2",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 50,
      brand: "Domace",
      rating: 4,
      numReviews: 10,
      description: "Height qualty product",
    },
    {
      _id: "3",
      name: "Name 3",
      category: "Pants",
      image: "/images/p3.jpg",
      price: 50,
      brand: "Domace",
      rating: 4.5,
      numReviews: 10,
      description: "Height qualty product",
    },
    {
      _id: "4",
      name: "Name 4",
      category: "Shirts",
      image: "/images/p4.jpg",
      price: 50,
      brand: "Domace",
      rating: 4.5,
      numReviews: 10,
      description: "Height qualty product",
    },
    {
      _id: "6",
      name: "Name 6",
      category: "Shirts",
      image: "/images/p6.jpg",
      price: 50,
      brand: "Domace",
      rating: 4.5,
      numReviews: 10,
      description: "Height qualty product",
    },
  ],
};

export default data;
